plugins {
    id 'org.springframework.boot'
    id 'com.google.cloud.tools.jib'
}

dependencies {
    implementation project(':muffin-wallet-api')
    implementation project(':muffin-wallet-data')
    implementation project(':muffin-wallet-data-api')
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework:spring-tx'
    implementation 'io.micrometer:micrometer-registry-prometheus'
    implementation 'org.mapstruct:mapstruct'
    implementation 'io.micrometer:micrometer-tracing-bridge-brave'
    implementation 'io.zipkin.reporter2:zipkin-reporter-brave'
    implementation 'net.logstash.logback:logstash-logback-encoder:7.4'
    annotationProcessor 'org.mapstruct:mapstruct-processor'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'io.cucumber:cucumber-java'
    testImplementation 'io.cucumber:cucumber-spring'
    testImplementation 'io.cucumber:cucumber-junit-platform-engine'
    testImplementation 'org.junit.platform:junit-platform-suite'
    testImplementation 'io.zonky.test:embedded-postgres'
    testImplementation 'io.zonky.test:embedded-database-spring-test'
}

test {
    useJUnitPlatform()
}

jib {
    to {
        image = 'ghcr.io/' + findProperty('ghcr.repository') + '/' + findProperty('rootProject.name')
    }
}
