---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: muffin-currency
  labels:
    app: muffin-currency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: muffin-currency
  template:
    metadata:
      labels:
        app: muffin-currency
    spec:
      containers:
      - name: muffin-currency
        image: userviktoriuss/muffin-currency:1.2.1
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /rate?from=PLAIN&to=CHOKOLATE
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /rate?from=PLAIN&to=CHOKOLATE
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: muffin-currency
spec:
  selector:
    app: muffin-currency
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: muffin-wallet
spec:
  type: ClusterIP
  selector:
    app: muffin-wallet
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: muffin-wallet
  labels:
    app: muffin-wallet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: muffin-wallet
  template:
    metadata:
      labels:
        app: muffin-wallet
    spec:
      volumes:
        - name: application-config-volume
          configMap:
            name: muffin-wallet
      containers:
        - name: muffin-wallet
          image: userviktoriuss/muffin-wallet:1.5.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: application-config-volume
              mountPath: /app/config
          envFrom:
            - secretRef:
                name: muffin-wallet
            - configMapRef:
                name: muffin-wallet-env
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Secret
metadata:
  name: muffin-wallet
data:
  SPRING_DATASOURCE_PASSWORD: bXVmZmluLXdhbGxldA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: muffin-wallet-env
data:
  JDK_JAVA_OPTIONS: -Dspring.config.additional-location=/app/config/application.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: muffin-wallet
data:
  application.yaml: |
    ---
    server:
      port: 8081
      address: 0.0.0.0

    spring:
      application:
        name: muffin-wallet
      datasource:
        url: jdbc:postgresql://host.containers.internal:5432/muffin_wallet
        username: muffin-wallet
      zipkin:
        base-url: http://zipkin:9411
    
    logging:
      pattern:
        level: "%5p [%X{traceId:-},%X{spanId:-}]"
      level:
        zipkin: DEBUG

    currency:
      service:
        url: http://muffin-currency:8083/rate
    management:
      tracing:
        sampling:
          probability: 1.0 # Sample 100% of traces for demo
      zipkin:
        tracing:
          endpoint: "http://zipkin:9411/api/v2/spans"
          connect-timeout: 1s
          read-timeout: 10s
      endpoints:
        web:
          exposure:
            include: '*'
      endpoint:
        health:
          probes:
            enabled: true
          show-details: always
      metrics:
        enable:
          http:
            server:
              requests: true
        distribution:
          percentiles-histogram:
            http:
              server:
                requests: true
        export:
          zipkin:
            enabled: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: muffin-wallet
spec:
  ingressClassName: nginx
  rules:
    - host: muffin-wallet.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: muffin-wallet
                port:
                  number: 8081
